project_name: fantasymarket
dist: ./bin

env:
  - GO111MODULE=on

before:
  hooks:
    - task build

builds:
- binary: fantasymarket
  dir: "."
  main: ./main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64

release:
  prerelease: auto
  name_template: "Release {{.Version}} 🎉"
