# game settings
game:
  ticksPerSecond: 0.1
  gameTimePerTick: 1h0m0s

# secret used to sign JWT tokens
tokenSecret: "secret"

logLevel: "debug"

# is this a development environment?
development: true