version: '2'

tasks:
  default:
    cmd: task --list
  help:
    cmd: task --list

  run:
    desc: "run fantasymarket"
    cmds:
      - go run main.go

  test:
    desc: "run all tests"
    cmds:
      - go test ./...

  lint:
    desc: "lint all files"
    cmds:
      - $(go env GOPATH)/bin/revive -formatter stylish -config .revive.toml -exclude=./vendor/... ./...

  install-linter:
    desc: "install the revive linter"
    env:
      GO111MODULES: off
    cmds:
      - go get -u github.com/mgechev/revive

  ci:
    desc: "run ci scripts (should only be run in ci environments)"
    cmds:
      - go mod verify
      - task install-linter
      - task lint
      - task test

  build:
    cmds:
      - go mod download
      - go generate ./...