version: '2'

tasks:
  run:
    env:
      development: false
    desc: "run fantasymarket"
    cmds:
      - go run main.go

  test:
    desc: "run all tests"
    cmds:
      - go test ./...

  lint:
    desc: "lint all files"
    cmds:
      - $(go env GOPATH)/bin/revive -formatter stylish -config .revive.toml -exclude=./vendor/... ./...

  install-linter:
    desc: "install the revive linter"
    env:
      GO111MODULES: off
    cmds:
      - go get -u github.com/mgechev/revive

  ci:
    desc: "run ci scripts (should only be run in ci environments)"
    cmds:
      - go mod download
      - task install-linter
      - task lint
      - task test

  build:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go generate ./...
      - go build -ldflags="-s -w" -i main.go -o bin/fantasymarket

  deploy-staging:
    cmds:
      - echo "deployment isn't setup yet"

  deploy-production:
    cmds:
      - echo "deployment isn't setup yet"
