version: '2'

tasks:
  run:
    env:
      development: false
    desc: "run fantasymarket"
    cmds:
      - go run main.go

  test:
    desc: "run all tests"
    cmds:
      - go test ./...

  test-coverage:
    desc: "run all tests"
    cmds:
      - go test -coverprofile coverage.out ./...

  lint:
    desc: "lint all files"
    cmds:
      - $(go env GOPATH)/bin/revive -formatter stylish -config .revive.toml -exclude=./vendor/... ./...

  install-deps:
    desc: "install all dependencies"
    cmds:
      - task: install-linter
      - task: insall-bindata

  install-linter:
    desc: "install the revive linter"
    env:
      GO111MODULES: off
    cmds:
      - go get -u github.com/mgechev/revive

  insall-bindata:
    desc: "install go-bindata"
    env:
      GO111MODULES: off
    cmds:
      - go get -u github.com/go-bindata/go-bindata/...

  ci:
    desc: "run ci scripts (should only be run in ci environments)"
    cmds:
      - go mod download
      - task: install-deps
      - task: lint

  build:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go generate ./...
      - go build -ldflags="-s -w" -o bin/fantasymarket -i main.go

  deploy-staging:
    cmds:
      - echo "deployment isn't setup yet"

  deploy-production:
    cmds:
      - echo "deployment isn't setup yet"
