name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    
    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Setup Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    
    - name: Install Taskfile
      uses: Arduino/actions/setup-taskfile@master
    
    - name: Run Tests
      run: task ci
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
