name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.1'
    - uses: Arduino/actions/setup-taskfile@master
    - run: task ci
