name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    
    - name: Install Taskfile
      uses: Arduino/actions/setup-taskfile@master
    
    - name: Run CI Scripts
      run: task ci

    - name: Run tests & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_COVERAGE }}
      with:
        coverageCommand: task test-coverage
        debug: true
        coverageLocations: |
          ${{github.workspace}}/coverage.out:gocov

    - name: Build Binary
      run: task build

    - name: Deploy (staging)
      if: github.ref == 'refs/heads/develop'
      run: task deploy-staging

    - name: Deploy (production)
      if: github.ref == 'refs/heads/master'
      run: task deploy-production

